CREATE TABLE sale_offers (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  type ENUM('BANNER', 'DEAL', 'BENEFIT') NOT NULL DEFAULT 'DEAL',
  badge VARCHAR(120) NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255) NULL,
  highlight VARCHAR(120) NULL,
  detail TEXT NULL,
  color VARCHAR(64) NULL,
  border_color VARCHAR(64) NULL,
  cta_label VARCHAR(120) NULL,
  cta_href VARCHAR(512) NULL,
  plan_id BIGINT NULL,
  magazine_id BIGINT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  starts_at DATETIME NULL,
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_sale_offers_type (type),
  INDEX idx_sale_offers_active (active),
  INDEX idx_sale_offers_sort (sort_order),
  FOREIGN KEY (plan_id) REFERENCES subscription_plans(id) ON DELETE SET NULL,
  FOREIGN KEY (magazine_id) REFERENCES magazines(id) ON DELETE SET NULL
);
